# version: '4.28.0'

# services:
#   cassandra:
#     image: cassandra:latest
#     container_name: my-cassandra
#     ports:
#       - "9042:9042"
#     volumes:
#       - ./cassandra-data:/var/lib/cassandra
#     environment:
#       - CASSANDRA_CLUSTER_NAME=Test Cluster
#       - CASSANDRA_DC=datacenter1

#   kafka:
#     image: apache/kafka:3.7.0
#     container_name: my-kafka
#     ports:
#       - "9092:9092"
#     environment:
#       KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
#       # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
#       # KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

version: '3'
services:
  springboot-app:
    ports:
      - 8080:8080
    build:
      context: .
      args:
        JAR_FILE: /Cart-Service.jar
    restart: always

  cassandradb:
    image: cassandra
    container_name: cassandra
    ports:
      - "9042:9042"
  
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"