#spring.application.name=PaymentMicroSerivce
spring:
  application:
    name: PaymentMicroservice
  datasource:
    url: jdbc:postgresql://localhost:5332/payments
    username: paymentcluster
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
      show-sql: true
  main:
    web-application-type: servlet